In [2]:
print("Hello World!")

Hello World!


# This is an introduction to Jupyter Lab

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
a = [1,2,3]
print(type(a))

<class 'list'>


In [5]:
a_arr = np.array(a)
print(type(a_arr))

<class 'numpy.ndarray'>


In [6]:
print(a)
print(a_arr)

[1, 2, 3]
[1 2 3]


In [7]:
b = [[1,2,3],[4,5,6],[7,8,9]]
b

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
b_arr = np.array(b)
b_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
b[0][2]

3

In [10]:
b_arr[0,2]

3

In [11]:
b_arr.shape

(3, 3)

In [12]:
c = np.zeros([3,4])
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
d = np.ones([2,5],'int16')
d

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)