# Homework 11

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from PIL import Image
import numpy as np
import simpleaudio as sa

## Question 1

### **First:** Picking RGB vectors in $\mathbb{R}^3$

let, our vectors be pure red, pure green, and pure blue (in that order).

$$
V_1 = (1, 0, 0) \\
V_2 = (0, 1, 0) \\
V_3 = (0, 0, 1)
$$

### **Second:** Proving they span $\mathbb{R}^3$

Firstly, we know these vectors combined will form black, so that maybe a proof that they span $\mathbb{R}^3$.

But let's prove it mathematically!

Let $w = (a, b, c) \in \mathbb{R}^3$. We can write $w$ as:

$$
w = (a, 0, 0) + (0, b, 0) + (0, 0, c) = a \cdot (1, 0, 0) + b \cdot (0, 1, 0) + c \cdot (0, 0, 1)
$$

So, $w$ is a linear combination of $V_1, V_2, V_3$. Therefore, they span $\mathbb{R}^3$.

### **Third:** Converting RGB to CMYK

In [2]:
#  ------- Conversion Functions  ------- 
def rgb_to_cmyk(r, g, b):
    k = 1 - max(r, g, b)
    if k == 1:
        return (0, 0, 0, 1)  # Pure black case
    c = (1 - r - k) / (1 - k)
    m = (1 - g - k) / (1 - k)
    y = (1 - b - k) / (1 - k)
    return (c, m, y, k)

#  ------- Define vectors sets  ------- 
RGB_basis = np.array([ 
    [1, 0, 0],  # V1
    [1, 1, 1],  # V2
    [0, 1, 1]   # V3
])

#  ------- Display Vectors in CMYK  -------
CMYK_basis = np.array([rgb_to_cmyk(*color) for color in RGB_basis])
print("CMYK vectors:")
print(CMYK_basis)

CMYK vectors:
[[0. 1. 1. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]


So our vectors converted to CMYK will be:

$$
\tilde{V_1} = (0, 1, 1, 0) \\
\tilde{V_2} = (0,0,0,0) \\
\tilde{V_3} = (1, 0, 0, 0)
$$

### **Fourth:** Proving they don't span $\mathbb{R}^4$

Consider CMYK's pure black vector: $x = (0, 0, 0, 1) \in \mathbb{R}^4$. Suppose $\tilde{V_1}, \tilde{V_2}, \tilde{V_3}$ span $\mathbb{R}^4$. Then, $x$ can be written as:

$$
x = a \cdot (0,1,1,0) + b \cdot (0,0,0,0) + c \cdot (1,0,0,0) \\ 
= (0,a,a,0) + (0,0,0,0) + (c,0,0,0) = (c,a,a,0)
$$

So for $ (0,0,0,1)= a\tilde{V_1}+b\tilde{V_2}+c\tilde{V_3} = (c,a,a,0)$, it mush be that $a0 + b0 + c0 = 1$, which is **not true**. 

Therefore, $\tilde{V_1}, \tilde{V_2}, \tilde{V_3}$ don't span $\mathbb{R}^4$.

## Question 2

In [3]:
# Define parameters
SAMPLE_RATE = 44100  # Sampling frequency (Hz)
DURATION = 0.35  # Duration of each note or chord (seconds)

# Function to generate a sine wave for a given frequency
def generate_tone(frequency, duration=DURATION, sample_rate=SAMPLE_RATE):
    t = np.linspace(0, duration, int(sample_rate * duration), False)
    wave = np.sin(2 * np.pi * frequency * t)
    wave *= 32767 / np.max(np.abs(wave))  # Normalize to 16-bit range
    return wave.astype(np.int16)

# Function to generate a chord by summing multiple sine waves
def generate_chord(frequencies, duration=DURATION, sample_rate=SAMPLE_RATE):
    t = np.linspace(0, duration, int(sample_rate * duration), False)
    wave = sum(np.sin(2 * np.pi * freq * t) for freq in frequencies)
    wave *= 32767 / np.max(np.abs(wave))  # Normalize to 16-bit range
    return wave.astype(np.int16)

# Function to play a sound buffer
def play_sound(wave):
    play_obj = sa.play_buffer(wave, num_channels=1, bytes_per_sample=2, sample_rate=SAMPLE_RATE)
    play_obj.wait_done()

# Frequencies for the B Minor scale (in Hz)
B_MINOR_SCALE = {
    "B": 493.88,
    "C#": 554.37,
    "D": 587.33,
    "E": 659.25,
    "F#": 739.99,
    "G": 783.99,
    "A": 880.00,
    "B_high": 987.77
}

Before we begin, let's define the vectors clearly (from the table). 

For $(B, C\#, D, E, F\#, G, A) \in \mathbb{R}^7$:

$$
\text{Bm} = (1,0,1,0,1,0,0) \\
\text{Cdim5} = (0,1,0,1,0,1,0) \\
\text{A6} = (0,0,1,0,1,0,1) \\
\text{Gmaj7} = (0,0,1,0,1,1,1)
$$

### **Part A**

Let $V = \mathbb{R}^7$. Suppose our 4 chord vectors are independent. Then for $a, b, c, d \in \mathbb{R}$:

$$
a \cdot \text{Bm} + b \cdot \text{Cdim5} + c \cdot \text{A6} + d \cdot \text{Gmaj7} = 0 \\
\implies a = b = c = d = 0
$$

Lets see if this is true:

$$
(a,0,a,0,a,0,0) + (0,b,0,b,0,b,0) + (0,0,c,0,c,0,c) + (0,0,d,0,d,d,d) \\ = (a, b, a+c+d, b, a+c+d, b+d, c+d)
$$

So,

$$
(a, b, a+c+d, b, a+c+d, b+d, c+d) = (0,0,0,0,0,0,0) \\
\implies a = b = a+c+d = b+d=  c+d = 0 \\
\implies a = b = c = d = 0
$$

Therefore, the 4 chord vectors are linearly independent.

### **Part B**

1. Proving the chords don't span $\mathbb{R}^7$.

For the chord vectors to span $\mathbb{R}^7$, we need at least 7 linearly independent vectors, since $\mathbb{R}^7$ has seven dimentions. (this is exactly the same as the previous question).

For example in the four vectors we have, the note E, has never been included independently. So for $(0,0,0,1,0,0,0) \in \mathbb{R}^7$, it can't be written as a linear combination of the four vectors. Because only Cdim5 includes E, which also includes G and C#.

Therefore, the four vectors don't span $\mathbb{R}^7$. 

2. Adding chords to span $\mathbb{R}^7$.

So we know that we need to add at least 3 more linearly independent vectors to span $\mathbb{R}^7$. I think the best way to do this is to add vectors that only include one note, which is not independently included in the other (like E as I mentioned above).

So, we can add the following vectors:

$$
C_1 = (0,0,0,1,0,0,0) \\
C_2 = (0,0,0,0,1,0,0) \\
C_3 = (0,0,1,0,0,0,0)
$$

3. Modifying the code

Maybe I'm not understanding the question correctly, but I think the chords defined in the code don't match the ones in the table. So I will redefine those, and add the new vectors.

In [4]:
# Define some chords using the B Minor scale
CHORDS = {
    # table's chords
    "Bm": ["B", "D", "F#"],
    "Cdim5": ["C#", "E", "G"],
    "A6": ["A", "D", "F#"],
    "Gmaj7": ["G", "A", "D", "F#"],
    # my chors
    "C1": ["G"],
    "C2": ["D"],
    "C3": ["F#"]
}

# Play individual notes
print("Playing B Minor Scale...")
for note, freq in B_MINOR_SCALE.items():
    print(f"Playing {note} ({freq} Hz)")
    wave = generate_tone(freq)
    play_sound(wave)

# Play chords
print("\nPlaying Chords...")
for chord, notes in CHORDS.items():
    freqs = [B_MINOR_SCALE[note] for note in notes]  # Get frequencies
    print(f"Playing {chord} ({', '.join(notes)})")
    wave = generate_chord(freqs)
    play_sound(wave)

print("Done!")

Playing B Minor Scale...
Playing B (493.88 Hz)
Playing C# (554.37 Hz)
Playing D (587.33 Hz)
Playing E (659.25 Hz)
Playing F# (739.99 Hz)
Playing G (783.99 Hz)
Playing A (880.0 Hz)
Playing B_high (987.77 Hz)

Playing Chords...
Playing Bm (B, D, F#)
Playing Cdim5 (C#, E, G)
Playing A6 (A, D, F#)
Playing Gmaj7 (G, A, D, F#)
Playing C1 (G)
Playing C2 (D)
Playing C3 (F#)
Done!


I'm not sure how to know if the new vectors are correct, or not... Because they should not necessarily sound the exact same. 

I checked if they are linear independent on paper, and they are. I showed that:

$$
a \cdot \text{Bm} + b \cdot \text{Cdim5} + c \cdot \text{A6} + d \cdot \text{Gmaj7} + e \cdot C_1 + f \cdot C_2 + g \cdot C_3 = 0 \\
\implies a = b = c = d = e = f = g = 0
$$

So I think they do span $\mathbb{R}^7$.

### **Part C**

In the context of chord vectors, I think linear dependence means that at least one chord in the set can be expressed as a combination of the others. This implies redundancy in the set, as the dependent chord does not add new information or unique harmonic content. For example, if we had a chord that could be formed by mixing Bm and A6, it would be linearly dependent on them, meaning that it doesn't make a new unique sound.